### ISSUE TITLE
Un-minable wagon

### ISSUE THREAD

**Issue by d0ob** [robot256/Vehicle-Wagon-2#11]
Hi again ! It's Friendch from the mod portal.
Here's my save, tell me if anything else. Hope you'll find something.
[1.0.zip](https://github.com/robot256/Vehicle-Wagon-2/files/7000318/1.0.zip)

**Comment by robot256** [comment]
Very strange.  Somehow that wagon ended up with the "minable" flag set to false.  I loaded the save and placed a new wagon right next to it, and I could mine it just fine.  What else did you do to the first wagon before you found it was unminable?

**Comment by d0ob** [comment]
I have the "half of the mod I hear about end up seeming indispensable" hillness... ^^

_Usually it goes until game become too unstable lol But I have less now, I made some cleaning ! 
That's a story I almost told in my comment because retrieving my save was a whole story lol_

Indeed ! Just tested myself too, with another wagon, and it goes flawlessly as you say... Not even reproducible, that's strange...
I really don't recall, but maybe I had other mod when I installed the wagon and had the issue than when that save has been made ? I don't think so, but I suppose that would be the only explanation... Because next to that, I don't recall doing anything special. I just tried to do as I remember I did, as some other nonsense, but nothing brings the issue again...

Well, I'm sorry that I can't say more, that it wasn't handy and that you did all that for nothing... 
If anything comes back to my mind... Thanks much for your time and consideration. (And, again, for the mod !)

**Comment by robot256** [comment]
You're welcome!  I kind of broke the million-mod habit because of all the ones that didn't update from one beta version to the next. Hopefully we are finished with that!

But since you mentioned it, let me tempt you with my other helper mods, Multiple Unit Train Control, Smart Artillery Wagons and Better Uncoupling Control; and my favorites, Automatic Coupling System, Dispatcher, and Cargo Ships

**Comment by d0ob** [comment]
Oh yes that's true, I always forgot that the game did not came out from beta long ago ! 
Well indeed, as in any-game, I hope there will not be another mod-breaking upodate anytime soon x) 

I was wondering why I see none of those on your mod portal ^^ Forgot that Vehicle wagon isn't on yours because its a maintenance !

- For the remote network I hesitated between Shortwave and the one I installed, RadioNetwork. (Wich, I still didn't used once, now I think of it lol) Would you be objective if I ask which one is the best ? ^^ 
- Figure that : I have installed cargo ship since then ! lol But it's the one on Schnurrebutz page, is yours an update, a rework ? 
- I was really tempted by Honk, but I was a bit afraid to hear horns all the time ^^ 
- And finally, do you recommend Multiple Unit Train Control because you saw that I'm a noob when it comes to building train routes? xD (between others ^^)
So indeed that's some I'll try ! Thanks for the suggests. (But don't tell me I have too many mods after that ! xD

**Comment by robot256** [comment]
Oh, by "favorites" I meant favorite other people's mods!  I have helped to debug Cargo Ships, though, and tried adding vehicle ferries to it (pretty complicated, didn't work exactly).

I kind of love hearing all the honks :)  they do fade with distance and you can adjust the volume.  I usually turn off the "stopping" sounds, and only include the "leaving station" sound.  I really like the fog horns I found for the cargo ships though.

The wireless signal transmission mods gave me a lot of trouble during updates, so I switched back and forth a couple times.  Radio Network is cool because you are more limited in distance and channels.  Shortwave gives you basically unlimited channels and no range limitation, so it's more like a creative mode thing.  Last time I checked, there was a bug in Radio Network that gave super high power consumption for no reason sometimes.

Multiple Unit Train Control was my first mod, so I recommend it to everybody :) It basically removes an intentional nerfing that the game devs added, which is just pain in some situations.

The last game I placed was Space Exploration, not very many different mods but way too much content!  To each their own.

**Comment by d0ob** [comment]
Oh I see ! Misunderstood ^^ 

Well you're indeed tempting me to try honk ! ^^ Doesn't quiet sound like what I pictured after all.

Space exploration, as some other big mod / overhaul, makes me a bit worried there is too much in it ! Part of the mods I removed today are some with lot of change or lot of new content, it was too soon in my Factorio jounrey, I decided to go back a bit to more vanilla. But I can't stop hearing about them, for sure I'll try them one day ! You play since long ? What about code ? 

In that sense, I also really liked the premises of the multiple aliens mods, like bob's, rampant, N-Evolution etc.. But I had a hard time making them work flawlessly, even less together, so it's only vanilla mobs now...

I also wanted to look for making my own personal mod, to reorganize my crafting menu, that really start to be total mess triggering my _OCD_ lol. I looked at every related mod's code, even asked to one of those mod's maker on the forum (Nironwolf,  when I saw his 5dim cats), who, really kindly, told me everything I should know ! But it's really overwhelming to me... =/ My coding knowledge don't go farther than translating local files and making minor changes in mods lol

**Comment by robot256** [comment]
I first played about 2.5 years ago, started modding after about a month (I like coding).  It's really simple compared to modding any other game!  I have taken several breaks since then, and my first 1kspm base had lots of different kinds of trains and ships and circuits.

**Comment by d0ob** [comment]
I bet you like ^^ 
Yes indeed I've read that devs have made their best to do a friendly modding scene, being coders themself ! I'm a fan of mods, giving so much more in any games they're provided, I wish I gave myself more motivation to learn to code and mod. Here, even known to be accessible, it's already a lot to read and understand ! Really daunting to me.

Damn ! I'm not close from my first mega base xD Even less since every time I feel I wrongly started, or I put / remove a mod that change too many things, I restart lol (Which i promise to myself yesterday that I wouldn't do anymore ! ) I'd love to see that ! would you agree if it was your turn to send your save ? =3

**Comment by robot256** [comment]
> Damn ! I'm not close from my first mega base xD Even less since every time I feel I wrongly started, or I put / remove a mod that change too many things, I restart lol (Which i promise to myself yesterday that I wouldn't do anymore ! ) I'd love to see that ! Would you agree if it was your turn to send your save ? =3

Here it is!  I'm pretty sure it only uses publicly available mods at the moment?  I did have to submit bug fixes for some of them before everything would work.  https://www.dropbox.com/s/qvrhyall8zw2i0g/110RailTwo_migration.zip?dl=0

> PS: If I take More Honks, and thus, its dependencies, your Honk's fork : Then I don't take original Honk, right ?
> And also, I don't fully understand about the configuration ^^ From the two inside map settings, which one I enable/disable ?

Yes, the forked Honk has the same name as the original inside the game, so it will conflict.  There is a separate button in the Settings menu for "Mod Settings", that has a list with a section for each mod.  There are three tabs for the three types of settings (startup, global, and player).
